




/*
*******************
    COMIENZO CLASE
*******************

*******************
REPASO DÍA ANTERIOR

    INTRODUCCION A BASE DE DATOS
        ALMACENAR Y ORDENAR UNA GRAN CANTIDAD DE DATOS, ACTUALIZAR INFORMACIÓN
        SQL EL LENGUAJE
        MYSQL ES GESTOR DE BASES DE DATOS

    TIPOS DE BASES DE DATOS
        BASE DE DATOS RELACIONALES
        EN CADA FILA HAY UNA INSTANCIA
        COLUMNA EL TIPO DE DATOS

    TIPO DE RELACIONES DE BASE DE DATOS
        1 A MUCHOS
        MUCHOS A MUCHOS
        1 A 1

    STACK AMP, APACHE, MYSQL, PHP
        APACHE SERVIDOR
        MYSQL GESTOR DE BASE DATOS
        PHP LENGUAJE PROGRAMACIÓN


FIN DEL REPASO
*******************


SINTAXIS BÁSICA DE CONSULTA DE BASE DE DATOS

ABRIMOS POWERSHELL, QUE SERÁ LA TERMINAL QUE USAREMOS
PARA LA CONSULTA DE LA BASE DE DATOS

EL PRIMER COMANDO QUE ME PERMITE INICIAR SESION MYSQL
ES OBLIGATORIO EL ; AL FINAL

    mysql -u root -p;

    PASSWORD: FullstackVigo En mac nada

PARA VER LAS BASES DE DATOS

    SHOW DATABASES;

LO HABITUAL ES ESCRIBIR EL CODIGO EN MAYUSCULAS

EL ; FINAL ES NECESARIO, HASTA QUE NO LO PONGAMOS NO 
SABRÁ CUAL ES EL FINAL DE LA SENTENCIA


CREAR UNA NUEVA BASE DE DATOS

    CREATE DATABASE peluqueria;
    SHOW DATABASES;

USAR UNA BASE DE DATOS

    USE peluqueria ;

PARA MOSTRAR LAS TABLAS

    SHOW TABLES;

PONER DIAPOSITIVA24

CREAR UNA NUEVA TABLA

    CREATE TABLE servicios(
    id INT(11) NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(60), //HASTA 60 CARACTERES, SI SE PASA LO CORTA Y COGE LOS 6O PRIMEROS
    precio DECIMAL(5,2), //100.00
    PRIMARY KEY (id)
    );

    DEBEN TENER UN IDENTIFICADOR UNICO, ID
    DEBEMOS INDICARLE EL TIPO DE DATO
    EL TIPO DE DATO QUE VAYA A USAR LO CONSULTO

    SHOW TABLES;

    DESCRIBE servicios; ME DA INFORMACIÓN DE LA TABLA

YA SABEMOS CREAR BASE DE DATOS Y TABLAS, VAMOS A VER
LAS OPERACIONES QUE PODEMOS HACER CON LOS DATOS DE LAS TABLAS

DIAPOSITIVA25

CRUD
        CREATE
        READ
        UPDATE
        DELETE

************ CREATE

INSERTAR REGISTROS
        INSERT INTO servicios (nombre,precio) 
        //EL id SE AUTOINCREMENTA, NO HAY QUE PASARLO
        VALUES ("Corte de Cabello de Adulto",15);

        INSERT INTO servicios (nombre,precio)
        VALUES ("Corte de Cabello Niño",12),
        ("Corte de Barba",8)

        //PARA AGREGAR MÁS DE UN REGISTRO A LA VEZ 

        !!!!!!!!!!!!
        EJERCICIO
        INSERTAR 5 REGISTROS MÁS DE PELUQUERIA EN LA TABLA SERVICIOS
        

************ READ

SELECCIONAMOS REGISTROS
        SELECT * FROM servicios;
        * PARA SELECCIONAR TODAS LAS COLUMNAS

        SI SOLO QUIERO SELECCIONAR UNA COLUMNA
        SELECT nombre FROM servicios;

        SELECT nombre,precio FROM servicios;

        COMO ORDENADOR UNA CONSULTA
        SELECT id,nombre,precio FROM servicios ORDER BY precio ASC; //ASC/DESC

        PODEMOS LIMITAR LA SELECCION
        SELECT * FROM servicios LIMIT 3;

        SELECCION QUE CUMPLA UNA CONDICION
        SELECT * FROM servicios WHERE id=2; //SE PUEDEN DAR OTRAS CONDICIONES

        = IGUAL QUE
        < MENOR QUE
        > MAYOR QUE
        <= MENOR IGUAL QUE
        >= MAYOR IGUAL QUE
        != DISTINTO QUE


!!!!!!!!!!!!!!!
EJERCICIO
MOSTRAR LOS REGISTROS CUYO PRECIO SEA MAYOR QUE 15




************ UPDATE

ACTUALIZAR REGISTROS
VAMOS A VARIAR EL PRECIO DEL Corte de Cabelle Hombre a 20€

        UPDATE servicios SET precio=20 WHERE id=1; // CON , ACTUALIZO LOS CAMPOS QUE QUIERA
        HAY QUE INDICAR SIEMPRE CON EL WHERE QUE REGISTRO ACTUALIZAMOS

        MOSTRAR LA TABLA PARA VER LA ACTUALIZACION




************ DELETE

        ELIMINAR REGISTROS
        DELETE FROM servicios WHERE id=1;
        IMPORTANTE DECIRLE CON EL WHERE QUE REGISTRO VAMOS A BORRAR

        !!!!!!!!!!
        EJERCICIO
        BORRAR EL ULTIMO REGISTRO QUE HABEIS AÑADIDO


        MOSTRAR TABLA
        SELECT * FROM servicios;

        SI AÑADO UN SERVICIO, CONTINUA POR EL ULTIMO, NO ME RELLENA
        LOS REGISTROS VACIOS

        !!!!!!!!!!!
        EJERCICIO
        AÑADIR UN NUEVO REGISTRO
        VER POR PANTALLA QUE ID RECIBE.

        !!!!!!!!!!
        EJERCICIO
        AÑADIR EL ID=1 DE NUEVO



*/